### ISSUE TITLE
Inline.dom could be undefined.

### ISSUE THREAD

**Issue by create3000** [andreasplesch/x_ite_dom#34]
In the function `appendInlineDOM` the property node.dom could be undefined and will cause an exception:
https://github.com/andreasplesch/x_ite_dom/blob/332b41c7c623c447cd054d61f747f42fb4ad56d8/src/x_ite_dom.js#L333
`TypeError: node.dom is undefined;`
when the Inline cannot load the url given, for instance the url field is empty or when the url is wrong.

There should be a check if the .dom property exists.

**Comment by andreasplesch** [comment]
That makes sense, I can add a check.

~~I am curious in what situations there may not be .dom property ? Should the property not be added in the parser ?
Perhaps an example would help to better understand.~~

**Comment by andreasplesch** [comment]
added check here with be6f30b5916875443b0d48ae3cee1e8115cf8222
and updated to version 1.2

**Comment by create3000** [comment]
Can confirm the change, it works now.

**Comment by andreasplesch** [comment]
Thanks.
