### ISSUE TITLE
--- --- at start in index.xhtml prevents page to work.

### ISSUE THREAD

**Issue by hermeticcab** [andreasplesch/x_ite_dom#35]
Hi,
in index.xhtml there are two lines of '---' at start which results in an error and prevents the page to work in a normal browser (firefox, chromium).
Is that intended?

```
---
---
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>dom access for x_ite</title>
```

Also there are a lot of not/no longer working examples in tests.

**Comment by andreasplesch** [comment]
These are for github pages' jekyll to force processing: https://jekyllrb.com/docs/front-matter/

**Comment by andreasplesch** [comment]
yeah, many tests broke. Could you please bisect which version or commit started to break this? For now, just go back to an older version of x_ite.

**Comment by andreasplesch** [comment]
It looks like it is this commit which broke things:
https://github.com/create3000/x_ite/commit/95c12e6584ca0a8a88168f4649abeb5ab241de94
This commit still works:
https://github.com/create3000/x_ite/commit/77cafb1341c4b4d601c8efd5dce6e16649640e30
Version  4.6.9a-961

**Comment by andreasplesch** [comment]
The latest x_ite works again with x_ite_dom.
